DROP TABLE IF EXISTS customer;

CREATE TABLE customer (
  id VARCHAR(250) PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) NOT NULL,
  password VARCHAR(250) NOT NULL
);
